version: '3'
services:

    php:
        image: php:8.3-fpm
        restart: always
        build:
            context: ./
            dockerfile: docker/Dockerfile
        volumes:
            - '.:/var/www/html'
            - './docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
        links:
            - db
        env_file:
            - .env
        depends_on:
            -   db


    nginx:
        image: nginx:latest
        restart: always
        ports:
            - '8082:80'
        volumes:
            - '.:/var/www/html'
            - './docker/nginx/conf.d:/etc/nginx/conf.d'
        links:
            - php

    db:
        image: mysql:5.7
        restart: always
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_CONNECTION=${DB_CONNECTION}
            - MYSQL_HOST=${DB_HOST}
            - MYSQL_ROOT_PASSWORD=030201qwe

        ports:
            - "3306:3306"
        volumes:
            - './volumes/mysql:/var/lib/mysql'

